### ISSUE TITLE
No output with Visio 2019

### ISSUE THREAD

**Issue by waltermaz** [Tony-SouthFLVMUG/vDiagram2.0#10]
There's no output when using Visio 2019.  Does this only work with Visio 2016?

**Comment by Tony-SouthFLVMUG** [comment]
I have tested it with 2019 and had no issues. Are you getting just a blank drawing or just a line? Can you check to see if the shapes file was added into your myshapes?

**Comment by waltermaz** [comment]
Glad to hear that it works with 2019.
The program completes quickly but there's nothing in the output folder.  And yes, the shapes file was added into the myshapes folder.

**Comment by Tony-SouthFLVMUG** [comment]
I'm out of pocket this weekend but would be open to doing a zoom call with you Monday to troubleshoot if you like.

**Comment by waltermaz** [comment]
That would be awesome!  Thanks and Have a great weekend!

**Comment by Tony-SouthFLVMUG** [comment]
Let me know what times & time zone you are in as well as your email address and I'll send over a meeting invite.

**Comment by waltermaz** [comment]
Any time after 10:30am works for me.  I'm in PT time zone.  Thanks!

**Comment by Tony-SouthFLVMUG** [comment]
Okay I am EST so that works perfect for me.

**Comment by Tony-SouthFLVMUG** [comment]
I'm free at 2pm EST if you want to jump on a Zoom meeting.

**Comment by waltermaz** [comment]
That would be great!  Thanks.
I had some progress yesterday... it finally created the visio file but the content only shows the vCenter Server icon.

**Comment by Tony-SouthFLVMUG** [comment]
Join Zoom Meeting
https://zoom.us/j/6681081284?pwd=ejVnVWFCU01RMVFscDBybi9CNWhKUT09

Meeting ID: 668 108 1284
Password: 482511
One tap mobile
+13126266799,,6681081284#,,,,0#,,482511# US (Chicago)
+19294362866,,6681081284#,,,,0#,,482511# US (New York)

Dial by your location
        +1 312 626 6799 US (Chicago)
        +1 929 436 2866 US (New York)
        +1 301 715 8592 US (Germantown)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
Meeting ID: 668 108 1284
Password: 482511
Find your local number: https://zoom.us/u/adCIEvbBds

**Comment by waltermaz** [comment]
I'm in zoom...

**Comment by waltermaz** [comment]
Works great!  Thanks again for the help!

**Comment by Tony-SouthFLVMUG** [comment]
Issue resolved via Zoom.
