### ISSUE TITLE
Diagram missing information from CSV files

### ISSUE THREAD

**Issue by ghost** [Tony-SouthFLVMUG/vDiagram2.0#11]
First I want to say that this script works great.  I just ran this on a vSphere 6.7 U3 environment and it produced the diagram but was missing information.  The diagram looks proper and shows the vCenter, datacenters, hosts, Storage volumes, etc, but the names of these items are not extracted from the CSV files and added to the diagram along with the object.  This makes editing the diagram afterwards tedious.  I know I'm being a bit nit picky, but your script has collected this info and I would like to see if fully used in the diagram output..

**Comment by Tony-SouthFLVMUG** [comment]
Closing as it seems you have resolved your issue with #12

**Comment by ghost** [comment]
This did not get resolved with the other issue.  The labels for the objects do not get added to the Visio diagram.  The vCenter, hosts, VM's, etc. are added to the diagram, but the text labels of what item is what does not get added.

**Comment by Tony-SouthFLVMUG** [comment]
Okay. Do you have availability to jump on a WebEx with me later this week?
Something doesn't seem right.

**Comment by ghost** [comment]
Certainly can.  I have time Wednesday 9/30 from 3 pm to 5 pm EST and Friday from 11 am to 5 pm EST as of right now.   Hopefully we can make this work.

**Comment by Tony-SouthFLVMUG** [comment]
I can do 4pm tomorrow. Send me your email address and I'll send you an
invite.

**Comment by petercrepeau** [comment]
Peter.crepeau@gmail.com

Best,

Peter Crepeau



On Sep 29, 2020, at 4:44 PM, Tony-SouthFLVMUG <notifications@github.com> wrote:


I can do 4pm tomorrow. Send me your email address and I'll send you an
invite.

**Comment by Tony-SouthFLVMUG** [comment]
Invite sent from tony.gonzalez@flagler.io
