### ISSUE TITLE
Update documentation regarding use of the script

### ISSUE THREAD

**Issue by ghost** [Tony-SouthFLVMUG/vDiagram2.0#12]
While using this script, I had to collect the info on one system and then generate the diagram on another system.  This process is not self evident.  Perhaps a note in the requirements may be best, but you need to enter the vCenter name exactly as you entered it on the system that you collected the data from for the tool to pick up on the files in the folder that you tell the tool your information is in.  This might help people better utilize your script if they find themselves in the same situation as me.

**Comment by Tony-SouthFLVMUG** [comment]
Peter thanks for the feedback. I will make sure we update the readme to reflect this on our next release.

**Comment by cyb3rbull** [comment]
> While using this script, I had to collect the info on one system and then generate the diagram on another system. This process is not self evident. Perhaps a note in the requirements may be best, but you need to enter the vCenter name exactly as you entered it on the system that you collected the data from for the tool to pick up on the files in the folder that you tell the tool your information is in. This might help people better utilize your script if they find themselves in the same situation as me.

Can you elaborate? You had to collect data on one system then draw on another system that was prepped to run the tool?

**Comment by ghost** [comment]
> > While using this script, I had to collect the info on one system and then generate the diagram on another system. This process is not self evident. Perhaps a note in the requirements may be best, but you need to enter the vCenter name exactly as you entered it on the system that you collected the data from for the tool to pick up on the files in the folder that you tell the tool your information is in. This might help people better utilize your script if they find themselves in the same situation as me.
> 
> Can you elaborate? You had to collect data on one system then draw on another system that was prepped to run the tool?

Yes.  Collect Data on one system, then transfer that data to another system that had Visio installed on it as the machine collecting data didn't/couldn't have Visio installed.
