### ISSUE TITLE
Issue with connection with certain CSV exports not completing

### ISSUE THREAD

**Issue by cyb3rbull** [Tony-SouthFLVMUG/vDiagram2.0#14]
I am running vsphere Version 6.7.0 Build 9433931 / ESXI 6.5.
The script runs but only on certain exports fail. I do notice that the connection fails then reconnects only with these reports. How can I best troubleshoot to resolve?
![vdiagramerror](https://user-images.githubusercontent.com/66438328/103715626-208d9780-4f8f-11eb-9676-36e093d4de88.png)

**Comment by Tony-SouthFLVMUG** [comment]
cyb3rbull - Those exports will only occur if you have thwm in your environment. I may have some free cycles tomorrow if you want to jump on a Zoom with me to troubleshoot.

**Comment by cyb3rbull** [comment]
I will zoom whenever just let me know when thank you so much. 

Send email to rogerdoger176@gmail.com and I will respond with my actual email for zoom thanks

**Comment by cyb3rbull** [comment]
Also not sure if I know what "thwmn" is.

**Comment by cyb3rbull** [comment]
I'm free for the rest of the day just a friendly reminder.

**Comment by Tony-SouthFLVMUG** [comment]
I didn't forget you. I've just been tied up with customers today. As soon as I can break free I will send you a link.

**Comment by cyb3rbull** [comment]
never mind I get it now the vcenter field in the vcenter info must match csv file name apologies thanks.

**Comment by cyb3rbull** [comment]
still cannot collect the csv files shown in screenshot

**Comment by Tony-SouthFLVMUG** [comment]
Do you have Datastore Clusters or Distributed Switches? If not those will not collect.

**Comment by cyb3rbull** [comment]
ok noted. When I try to draw the diagram I get blank drawings.

**Comment by Tony-SouthFLVMUG** [comment]
can you check your MyShapes folder and make sure the vDiagram_2.0.10.vssx file is present? We have seen issues where the script either doesn't copy the file over or the folder is being re-directed elsewhere

**Comment by cyb3rbull** [comment]
I do not

**Comment by Tony-SouthFLVMUG** [comment]
try copying that file to your MyShapes and run the tool again. Let me know if that works. Sorry I haven't been able to WebEx or Zoom, I have been tied up with customer stuff the past 2 days.

**Comment by cyb3rbull** [comment]
No worries I will try and let you know I appreciate any time you spare.

**Comment by cyb3rbull** [comment]
BOOM thanks that was it
