### ISSUE TITLE
Vision Line

### ISSUE THREAD

**Issue by aquriusmb** [Tony-SouthFLVMUG/vDiagram2.0#15]
The CSV export with all the data and I confirmed that the shapes file is in the right location but when I export to Visio all I get is a right angle line.

**Comment by Tony-SouthFLVMUG** [comment]
aquriusmb Please double check that the shapes file was copied to MyShapes. We have seen that as an issue numerous times as well as verify that Visio was installed in English as this also has been an issue.

**Comment by aquriusmb** [comment]
Confirmed that shapes file is in the proper location. Also this is with Visio 2019 and powercli 6.5.2

**Comment by Tony-SouthFLVMUG** [comment]
can you run it again with -logdraw and send me the log output? That will help me troubleshoot this a bit better.

Powershell command will be vDiagram_2.0.10.ps1 -logdraw , once the draw completes it will create a log file in the same directory as the drawing.

**Comment by aquriusmb** [comment]
Solved!

**Comment by Tony-SouthFLVMUG** [comment]
How did you solve?

**Comment by aquriusmb** [comment]
My mistake. I thought the shapes file needed to be in the default for Visio but it is looking for it in C:\My Shapes\.

**Comment by Tony-SouthFLVMUG** [comment]
should be default, but if that worked for you.
