### ISSUE TITLE
Sometimes Label Text is Gone

### ISSUE THREAD

**Issue by DennisFaucher** [Tony-SouthFLVMUG/vDiagram2.0#17]
Thanks for the awesome script. I scanned one vCenter and all the label text made it from the CSV to the Visio. I scanned a different larger vCenter and the label text did not make it from the CSV to the Visio. CSV attached. TIA.
[vcenter-blue.sddc2.wwtpoc.local-VmHostExport.csv](https://github.com/Tony-SouthFLVMUG/vDiagram2.0/files/6518592/vcenter-blue.sddc2.wwtpoc.local-VmHostExport.csv)

**Comment by jtrainmar** [comment]
Can you tell us the size of the environment? # of vCenters/Hosts/VMs?

We have seen this happen before, and is usually caused by an incorrect shapes file.

**Comment by DennisFaucher** [comment]
Yes, it looks like I attached the wrong CSV above. No issues with my small Home Lab, but issue with a larger environment. I have attached the correct CSV here. 1 vCenter, 103 VMs, 1 Data Center, 4 hosts, 1 cluster
[vcenter-blue.sddc2.wwtpoc.local-VmExport.csv](https://github.com/Tony-SouthFLVMUG/vDiagram2.0/files/6534857/vcenter-blue.sddc2.wwtpoc.local-VmExport.csv)

**Comment by Tony-SouthFLVMUG** [comment]
Hey Dennis. Sorry I have been out of town on vacation and came back to a ton of work. Can you share a screenshot of what you are experiencing? If you prefer not to share here you can always email us vdiagramproject@gmail.com

**Comment by DennisFaucher** [comment]
That's wonderful. I hope you had a great vacation. This is _not_ urgent. Here are the details:
* Windows 10
* Visio Standard 2019
* vCenter 7.0.2
* First run of vDiagram - labels on images (attached)
* Second run of vDiagram - no labels on images (attached)

I have also attached a few of my CSVs for testing. The name of my vCenter is vcenter (That seemd to be important for the CSV validation)

TIA

![vDiagram - Labels](https://user-images.githubusercontent.com/9034190/119833454-20a21b80-becd-11eb-9a4c-a99b0f48a393.png)
![vDiagram - No Labels](https://user-images.githubusercontent.com/9034190/119833462-21d34880-becd-11eb-866c-59ae44f230ad.png)
[vcenter-VmExport.csv](https://github.com/Tony-SouthFLVMUG/vDiagram2.0/files/6554342/vcenter-VmExport.csv)
[vcenter-VmHostExport.csv](https://github.com/Tony-SouthFLVMUG/vDiagram2.0/files/6554343/vcenter-VmHostExport.csv)

**Comment by Tony-SouthFLVMUG** [comment]
Dennis -  Are we good to close this issue out now?

**Comment by DennisFaucher** [comment]
Yes. Thank you for your help. I'll close.

Sincerely,
Dennis Faucher
978-621-7217

**Comment by DennisFaucher** [comment]
PEBCAK
I reinstalled the entire stack (OS, Repo) and labels returned. Thanks for all the help and the great software.
