### ISSUE TITLE
Visio 2016 not drawing after successful export of vcenter

### ISSUE THREAD

**Issue by barendw** [Tony-SouthFLVMUG/vDiagram2.0#19]
Successfully export vcenter csv files. Drawing completes, Visio 2016 opens but no drawings.

**Comment by Tony-SouthFLVMUG** [comment]
barendw,

Can you share a screenshot of what the output looks like? Also can you validate the the shapes file was copied into your MyShapes Folder?

**Comment by barendw** [comment]
Hi Tony. Copied the shape files to MyShapes Folder and working!
Many thanks!
