### ISSUE TITLE
Generating Visio seems to be stuck on creating first document

### ISSUE THREAD

**Issue by vierling** [Tony-SouthFLVMUG/vDiagram2.0#23]
Generating Visio seems to be stuck on creating first document: vCenter to Linked vCenter Visio Drawing. Been stuck there for 30 minutes.
![image](https://user-images.githubusercontent.com/39954191/131510034-ad21cc2a-782c-4ae3-a30c-fd8c5cc945e0.png)

**Comment by Tony-SouthFLVMUG** [comment]
Can you try running it with the -debug -logdraw switches? The -debug will not shrink the PowerShell window and the -logdraw will create a log output in the directory where the PowerShell script is located. This will help to troubleshoot what is going on.

**Comment by vierling** [comment]
Thanks for the suggestion, I ran it again with those switches and was able to see what was going on. The problem for me was I used the hostname of the vcenter instead of the IP address.  For what ever reason, using the hostname wouldn't collect all the data, but when I used the IP address, it seems to work fine.  Thanks for your help!
