### ISSUE TITLE
Use official VMware stencils

### ISSUE THREAD

**Issue by benwa** [Tony-SouthFLVMUG/vDiagram2.0#24]
Would you consider using the [official VMware stencils](https://github.com/rainpole/vmware-stencils) for output?

**Comment by Tony-SouthFLVMUG** [comment]
Ben we are working on an option for using the VVD shapes so stay tuned for that. If the VVD is not what you are looking for then unfortunately there are no "official shapes" from VMware.

**Comment by benwa** [comment]
That's exactly what I was hoping the hear. Thank you!

**Comment by Tony-SouthFLVMUG** [comment]
We are presenting on vDiagram Standard, SRM & Horizon at the South Florida VMUG UserCon on Sept 14th and are hoping to have it released by then.

**Comment by Tony-SouthFLVMUG** [comment]
@benwa check out the latest release 2.0.12 that has an option to select the shapefile you would like to use. We released it a few days ago.
