### ISSUE TITLE
CSV Validation Errors

### ISSUE THREAD

**Issue by kanoble88** [Tony-SouthFLVMUG/vDiagram2.0#25]
I've been trying to run the CSV Validation however, none of the CSV's that 've collected from the network are being detected.  I've tried with just 1 CSV and I've tried importing multiple but they don't seem to be detected. When I try to do a import I always get the same error though:

> Import-Csv : Could not find file 
'C:\NewOutputForTest\-VmExport.csv'.
At C:\vDiagram2.0-master\vDiagram2.0-master\vDiagram_2.0.12.ps1:4037 char:12
+     $SrmVMs = Import-Csv $SrmVMsFile
+               ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Import-Csv], FileNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ImportCsvCommand
 
You cannot call a method on a null-valued expression.
At C:\vDiagram2.0-master\vDiagram2.0-master\vDiagram_2.0.12.ps1:4038 char:43
+ ... = ( $SrmVMs | Where-Object { $_.SRM.contains("placeholderVm") } ).Cou ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

I've also tried collecting CSV's by connecting to vCenter with hostname and IP and both give the same results.

Thanks

**Comment by Tony-SouthFLVMUG** [comment]
@kanoble88 I'm not totally sure what you have going on there but if you are available to jump on a Webex/Zoom with me tomorrow after 11am EST I can try and figure out what you have going on.

**Comment by kanoble88** [comment]
I think I was able to figure out what was causing the error.  I wasn't connected to vCenter when doing the check for CSV's. Once I connected to vCenter I the CSV checks went through and I was able to kick off a drawing.  Is there any way to bypass having to be connected to vcenter to check for the CSV's and create the drawing?

**Comment by Tony-SouthFLVMUG** [comment]
You only have to be connected to collect. You do however have to put the vCenter info exactly as you did when you collected in order to so the validation, this is due to the csv files containing the vCenter name. This was done by design for those that have multiple vCenters that they work with.

**Comment by kanoble88** [comment]
That is what I was doing wrong then.  It is working now! Thank you!

**Comment by Tony-SouthFLVMUG** [comment]
Are you good with me closing this issue then?
